# Generated by Django 2.0.2 on 2018-09-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsusers',
            options={},
        ),
    ]
