# Generated by Django 2.1 on 2018-10-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180910_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'NewsLetter Users',
                'ordering': ['-id'],
            },
        ),
    ]
