# Generated by Django 2.1 on 2018-10-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_newsletterusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetterUsers',
        ),
    ]
